services:
  # API .NET (Dockerfile en la raíz)
  - type: web
    name: celscrapper-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}

  # Sitio estático (sirve CelTechScrapper/web/home.html)
  - type: web
    name: celscrapper-web
    runtime: static
    rootDir: ./CelTechScrapper/web
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /home.html
